repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
  - id: check-added-large-files
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.7
  hooks: [id: clang-format]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.4.10
  hooks: [id: ruff, id: ruff-format]
