@Library("jenlib") _

runOnSlave(label: "frontend") {
	wafSetup(projects: ["fisch"])
}

stage("Build & Test") {
	onSlurmResource([partition: "jenkins", "cpus-per-task": 8]) {
		dir("genpybind") {
			inSingularity(app: "visionary-dls") {
				jesh "./waf configure build"
			}
		}
	}
}
